doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        types:
            uuid: Ramsey\Uuid\Doctrine\UuidType

    orm:
        auto_generate_proxy_classes: false
        auto_mapping: false
        mappings:
            App\Modules\Players\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Players/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Modules\Players\Domain'
                alias: Players
            App\Modules\Launches\Domain:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Modules/Launches/Infrastructure/Persistence/Doctrine'
                prefix: 'App\Modules\Launches\Domain'
                alias: Launches

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
