version: '3.9'

networks:
  bowling_kata_pop_network:

services:
  mysql:
    container_name: bowling_kata_pop-mysql
    image: mariadb:10.7.4
    ports:
      - "3360:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    healthcheck:
      test: ["CMD", "mysqladmin", "--user=root", "--password=", "--host=127.0.0.1", "ping", "--silent"]
      interval: 2s
      timeout: 10s
      retries: 10
    command: ["--default-authentication-plugin=mysql_native_password"]
    networks:
      - bowling_kata_pop_network

  backend_php:
    container_name: bowling_kata_pop-backend_php
    user: "${UID}:${GID}"
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8040:8040"
    volumes:
      - .:/app:delegated
    command: symfony serve --port=8040
    networks:
      - bowling_kata_pop_network

