################################################
#--------------- API CONTROLLER ---------------#
################################################
get_health-check:
    path: /api/health-check
    controller: App\Controller\API\HealthCheck\GetHealthCheckController
    methods:  [GET]

post_player:
    path: /api/player
    controller: App\Controller\API\Players\PostPlayerController
    methods:  [POST]
    format: application/json

post_player_launch:
    path: /api/player/launch
    controller: App\Controller\API\Launch\PostLaunchController
    methods:  [POST]
    format: application/json

get_player_score:
    path: /api/player/{player_id}/score
    controller: App\Controller\API\Players\GetPlayerScoreController
    methods:  [GET]

################################################
#--------------- WEB CONTROLLER ---------------#
################################################
get_home:
    path: /
    controller: App\Controller\WEB\Home\GetHomeController
    methods:  [GET]