get_health-check:
    path: /health-check
    controller: App\Controller\HealthCheck\GetHealthCheckController
    methods:  [GET]

post_player:
    path: /player
    controller: App\Controller\Player\PostPlayerController
    methods:  [POST]
    format: application/json